version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - bodyclose
    - gocritic
    - gosec
    - govet
    - nestif
    - nlreturn
    - revive
    - rowserrcheck
  settings:
    gosec:
      excludes:
        - G104
        - G107
        - G115
        - G304
        - G401
        - G501
    revive:
      rules:
      - name: package-comments
        disabled: true

